<?php
/** @var $block \Magebit\Faq\Block\QuestionList */ ?>
<h1><?php
    echo __('Frequently Asked Questions') ?></h1>
<ul class="faq-list" id="element">
    <?php
    /** @var $faq \Magebit\Faq\Model\Question */ ?>
<!--    <div id="faq-accordion" class="faq-list">-->
        <?php
        foreach ($block->getFaqQuestions() as $faq): ?>
            <li class="faq-list-item" data-role="collapsible">
                <h3 class="faq-item-question" data-role="trigger">
                    <?php
                    echo $faq->getQuestion() ?>
                </h3>
                <div class="faq-item-content" data-role="content">
                    <div class="faq-item-answer">
                        <?php
                        echo $faq->getAnswer(); ?>
                    </div>
                    <div class="faq-item-meta">
                        <strong><?php
                            echo __('Updated at:') ?></strong> <?php
                        echo $faq->getUpdatedAt() ?>
                    </div>
                </div>
            </li>
        <?php
        endforeach; ?>
<!--    </div>-->
</ul>


<script>
    require([
        'jquery',
        'accordion'], function ($) {
        $("#element").accordion();
    });
</script>

<!--<script>-->
<!--    require([-->
<!--        'jquery'-->
<!--    ], function ($) {-->
<!--        $(document).ready(function () {-->
<!--            // Initially hide all FAQ content-->
<!--            $('.faq-item-content').hide();-->
<!---->
<!--            // Variable to keep track of the currently open content-->
<!--            var currentlyOpenContent = null;-->
<!---->
<!--            $('#faq-accordion .faq-list-item .faq-item-question').on('click', function () {-->
<!--                var content = $(this).next('.faq-item-content');-->
<!---->
<!--                // Check if there's an open item and it's not the current item-->
<!--                if (currentlyOpenContent && currentlyOpenContent.not(content).length) {-->
<!--                    currentlyOpenContent.slideUp(); // Hide the previously opened content-->
<!--                }-->
<!---->
<!--                // Toggle the current item's content visibility-->
<!--                content.slideToggle();-->
<!---->
<!--                // Update the currently open content reference-->
<!--                if (currentlyOpenContent && currentlyOpenContent.is(content)) {-->
<!--                    currentlyOpenContent = null; // No content is open now-->
<!--                } else {-->
<!--                    currentlyOpenContent = content; // Update the reference to the new open content-->
<!--                }-->
<!--            });-->
<!--        });-->
<!--    });-->
<!--</script>-->
