<?php
/**
 * @copyright Copyright (c) 2024 Magebit (https://magebit.com/)
 * @author info@magebit.com
 * @license GNU General Public License ("GPL") v3.0
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var TemplateEngineInterface $this */
/** @var PageList $block */
/** @var InlineUtilInterface $csp */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

use Magebit\PageListWidget\Block\Widget\PageList;
use Magento\Csp\Api\InlineUtilInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Framework\View\TemplateEngineInterface;

?>

<div class="cms-page-list">
    <?php if($block->getTitle()): ?>
    <h2><?= $escaper->escapeHtml($block->getData('title')) ?></h2>
    <?php endif; ?>

    <?php $cmsPages = $block->getCmsPages(); ?>
    <?php if($cmsPages->getSize() > 0): ?>
    <ul>
        <?php foreach($cmsPages as $page): ?>
        <li>
            <a href="<?= $block->getUrl(null, ['_direct' => $page->getIdentifier()]);?>">
                <?= $escaper->escapeHtml($page->getTitle())?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
    <?php else: ?>
    <p>No CMS pages available...</p>
    <?php endif; ?>
</div>
